import { randomBytes } from "node:crypto";
import { chmod, mkdir, open, readFile, stat, unlink, writeFile } from "node:fs/promises";
import { dirname, isAbsolute, join, resolve } from "node:path";
import {
  DEFAULT_EVIDENCE_S3_MAX_UPLOAD_BYTES,
  DEFAULT_EVIDENCE_S3_TIMEOUT_MS,
  EVIDENCE_S3_SUPPORTED_UPLOAD_BYTES_PER_SECOND,
  MAX_EVIDENCE_S3_UPLOAD_BYTES,
  MAX_EVIDENCE_S3_TIMEOUT_MS,
  MAX_EVIDENCE_UPLOAD_BYTES,
} from "../../evidence/s3-settings.js";

export const CONFIG_INIT_PROFILES = ["demo", "postgres", "ldap"] as const;
export type ConfigInitProfile = (typeof CONFIG_INIT_PROFILES)[number];

export interface ConfigInitInput {
  collabRoot: string;
  cwd?: string;
  output: string;
  profile?: ConfigInitProfile;
  force?: boolean;
  nonInteractive?: boolean;
  confirmOverwrite?: () => Promise<boolean>;
}

export interface ConfigInitResult {
  outputPath: string;
  profile: ConfigInitProfile;
  createdDirectories: string[];
  overwritten: boolean;
}

const HEADER = `# Generated by cd-collab config:init.
# Configuration SHAPE only. npm run doctor does not contact PostgreSQL, LDAP,
# Vercel, employer gateways, or model providers, and does not prove compatibility.
# Keep production credentials as secret-store placeholders. Never commit this file.

`;

function s3EvidenceComments(): string {
  return `# Optional S3-compatible evidence bytes. Server-side only; filesystem is the
# default when COLLAB_EVIDENCE_PROVIDER is absent. Doctor validates this block
# but does not contact the bucket. Startup and /ready ping the selected bucket.
# COLLAB_EVIDENCE_ROOT stays local server-owned control state in either mode.
# Filesystem mode rejects every present COLLAB_EVIDENCE_S3_* name, even if its
# value is empty: remove the S3 names when returning to filesystem mode.
# COLLAB_EVIDENCE_MAX_UPLOAD_BYTES is accepted in both modes. Filesystem
# defaults to 536870912 bytes / 512 MiB and retains the protocol ceiling of
# ${MAX_EVIDENCE_UPLOAD_BYTES} bytes / 5 GiB. S3 v1 instead validates a
# conservative request-time upload envelope: no more than
# floor(COLLAB_EVIDENCE_S3_TIMEOUT_MS / 1000) *
# ${EVIDENCE_S3_SUPPORTED_UPLOAD_BYTES_PER_SECOND} bytes. With both values
# unset, S3 defaults to ${DEFAULT_EVIDENCE_S3_MAX_UPLOAD_BYTES} bytes / 30 MiB
# at ${DEFAULT_EVIDENCE_S3_TIMEOUT_MS} ms. Its largest accepted pair is
# ${MAX_EVIDENCE_S3_UPLOAD_BYTES} bytes / 120 MiB at
# ${MAX_EVIDENCE_S3_TIMEOUT_MS} ms. Multipart upload is used for streams above
# one SDK part; the 5 GiB value is only a protocol ceiling, not a supported S3 v1
# operating size.
# The 1 MiB/s validation envelope does not guarantee success; actual networks
# or object stores may require a lower max. Legacy JSON/base64 evidence upload
# and JSON bytes download remain capped at exactly 1,000,000 decoded bytes.
# The object-store role must allow bucket readiness/list plus GetObject,
# PutObject, and multipart upload/abort for larger unknown-length streams.
# DeleteObject is required for staging, journal, and rollback cleanup.
# It is not a user-facing delete feature.
# There is no retention, lifecycle, migration, or multi-provider failover.
# COLLAB_EVIDENCE_PROVIDER=s3
# COLLAB_EVIDENCE_S3_ENDPOINT=https://s3.example.test
# COLLAB_EVIDENCE_S3_REGION=garage
# COLLAB_EVIDENCE_S3_BUCKET=war-room-evidence
# Prefer a dedicated bucket. A prefix is normalized with one trailing slash,
# but the required HeadBucket permission can make listing a broader boundary.
# COLLAB_EVIDENCE_S3_PREFIX=assigned-prefix
# Exact 0/1. Custom endpoints default to path-style; AWS-managed endpoints do not.
# COLLAB_EVIDENCE_S3_FORCE_PATH_STYLE=1
# Exact 0/1; default 0. Use 1 only for a trusted local HTTP evaluation endpoint.
# COLLAB_EVIDENCE_S3_ALLOW_HTTP=0
# Absolute regular PEM CA bundle, maximum 1 MiB. The S3 request handler uses
# Node's TLS ca option, which replaces the default trust store for that
# connection. To trust both public roots and an internal CA, mount one combined
# PEM bundle into the server process. Certificate verification stays enabled.
# COLLAB_EVIDENCE_S3_CA_FILE=/etc/ssl/certs/s3-internal-ca.pem
# Smithy connection timeout and absolute requestTimeout, 1000..120000 ms.
# requestTimeout covers PutObject, CopyObject, and multipart requests through response headers.
# COLLAB_EVIDENCE_S3_TIMEOUT_MS=${DEFAULT_EVIDENCE_S3_TIMEOUT_MS}
# S3 upload cap for the timeout above. HTTP transfer remains guarded separately
# for one hour, and unknown-length streams remain count-enforced.
# COLLAB_EVIDENCE_MAX_UPLOAD_BYTES=${DEFAULT_EVIDENCE_S3_MAX_UPLOAD_BYTES}
# Required in S3 mode; no default. static or default_chain. default_chain
# rejects all static COLLAB_EVIDENCE_S3_* credential names below.
# COLLAB_EVIDENCE_S3_CREDENTIALS_MODE=static
# Exactly one source per credential: direct environment value, _FILE, or
# absolute file:/... _REF (file:// is refused). _FILE/_REF targets must be
# owner-only regular files on Unix; relative paths and symlinks are refused.
# Direct names also exist for orchestrator injection, but never put secret
# values in this file: COLLAB_EVIDENCE_S3_ACCESS_KEY_ID,
# COLLAB_EVIDENCE_S3_SECRET_ACCESS_KEY, COLLAB_EVIDENCE_S3_SESSION_TOKEN.
# secret-store-sourced — mount owner-only files; never commit real keys.
# COLLAB_EVIDENCE_S3_ACCESS_KEY_ID_FILE=/run/secrets/evidence-s3-access-key-id
# COLLAB_EVIDENCE_S3_SECRET_ACCESS_KEY_FILE=/run/secrets/evidence-s3-secret-access-key
# COLLAB_EVIDENCE_S3_SESSION_TOKEN_FILE=/run/secrets/evidence-s3-session-token
# COLLAB_EVIDENCE_S3_ACCESS_KEY_ID_REF=file:/run/secrets/evidence-s3-access-key-id
# COLLAB_EVIDENCE_S3_SECRET_ACCESS_KEY_REF=file:/run/secrets/evidence-s3-secret-access-key
# COLLAB_EVIDENCE_S3_SESSION_TOKEN_REF=file:/run/secrets/evidence-s3-session-token
`;
}

function ldapBindSecretLine(): string {
  return `# ${["COLLAB_LDAP_BIND", "PASSWORD"].join("_")}=replace-from-secret-store`;
}

function ldapAdCompatibilityComments(): string {
  return `# Optional AD-compatible resolution. UPN suffix and NetBIOS are never derived from a DN.
# COLLAB_LDAP_USER_SEARCH_BASE=ou=people,dc=example,dc=test
# COLLAB_LDAP_USER_SEARCH_FILTER=(sAMAccountName={0})
# COLLAB_LDAP_USER_RESOLUTION=service_bind_search,upn,domain_backslash
# COLLAB_LDAP_UPN_SUFFIX=example.test
# COLLAB_LDAP_NETBIOS_DOMAIN=EXAMPLE
# COLLAB_LDAP_MEMBER_ATTR=memberOf
# COLLAB_LDAP_ATTR_DISPLAY_NAME=cn
# COLLAB_LDAP_ATTR_EMAIL=mail
# COLLAB_LDAP_ATTR_ROLE_TITLE=title
# COLLAB_LDAP_ATTR_TEAM=departmentNumber
# Bind secret: environment value, ${["COLLAB_LDAP_BIND", "PASSWORD_FILE"].join("_")}, or a file: reference. Configure exactly one.
# With no service bind, groups found during login remain in that session until re-authentication.
# Configure the service bind when immediate directory-membership refresh is required.
`;
}

function isProfile(value: string | undefined): value is ConfigInitProfile {
  return CONFIG_INIT_PROFILES.includes(value as ConfigInitProfile);
}

function renderDemo(): string {
  return `${HEADER}# Profile: local demo / synthetic War Room
COLLAB_HOST=127.0.0.1
COLLAB_PORT=8787
COLLAB_SERVICE_NAME=cd-collab
COLLAB_EVIDENCE_ROOT=.data/evidence
COLLAB_COOKIE_SECURE=0
COLLAB_STORAGE=sqlite
COLLAB_SQLITE_PATH=.data/collab.sqlite
COLLAB_AUTH_MODE=local
COLLAB_LOCAL_USERS='[{"username":"lead","password":"CHANGE-ME","displayName":"Case Lead","groups":["local:case-lead"]}]'
COLLAB_GROUP_ROLE_MAP=local:case-lead=case-lead

# Optional UI assets after npm run build (unset = API-only)
# COLLAB_STATIC_DIR=web/dist

# secret-store-sourced — placeholders, not a live connectivity claim
# COLLAB_DATABASE_URL=postgres://collab_app:replace-from-secret-store@127.0.0.1:5432/collab
# COLLAB_MIGRATE_DATABASE_URL=postgres://collab_migrator:replace-from-secret-store@127.0.0.1:5432/collab

# Encrypted directory only (ldaps:// or ldap:// + COLLAB_LDAP_STARTTLS=1).
# COLLAB_LDAP_URL=ldaps://directory.example.test:636
# COLLAB_LDAP_USER_DN_TEMPLATE=uid={username},ou=people,dc=example,dc=test
# COLLAB_LDAP_GROUP_SEARCH_BASE=ou=groups,dc=example,dc=test
# COLLAB_LDAP_BIND_DN=
${ldapBindSecretLine()}
${ldapAdCompatibilityComments()}
# COLLAB_GROUP_ROLE_MAP=cn=viewers,ou=groups,dc=example,dc=test=viewer;cn=contributors,ou=groups,dc=example,dc=test=contributor;cn=admins,ou=groups,dc=example,dc=test=admin

# Optional ContextDesk host bridge (filesystem path only; doctor does not execute it)
# COLLAB_BRIDGE_BIN=

# Optional live profile catalog (syntax only; doctor does not call providers)
# COLLAB_LIVE_PROFILE_CATALOG=
# COLLAB_PROFILE_CATALOG=
# COLLAB_LIVE_PROFILES=
# COLLAB_LIVE_VERCEL=0

${s3EvidenceComments()}`;
}

function renderPostgres(): string {
  return `${HEADER}# Profile: PostgreSQL deployment shape (database is not contacted by doctor)
COLLAB_HOST=127.0.0.1
COLLAB_PORT=8787
COLLAB_SERVICE_NAME=cd-collab
COLLAB_EVIDENCE_ROOT=.data/evidence
COLLAB_COOKIE_SECURE=1
COLLAB_STORAGE=postgres
COLLAB_AUTH_MODE=ldap
COLLAB_STATIC_DIR=web/dist

# secret-store-sourced — placeholders, not a live connectivity claim
COLLAB_DATABASE_URL=postgres://collab_app:replace-from-secret-store@127.0.0.1:5432/collab
COLLAB_MIGRATE_DATABASE_URL=postgres://collab_migrator:replace-from-secret-store@127.0.0.1:5432/collab

# Encrypted directory only.
COLLAB_LDAP_URL=ldaps://directory.example.test:636
COLLAB_LDAP_USER_DN_TEMPLATE=uid={username},ou=people,dc=example,dc=test
COLLAB_LDAP_GROUP_SEARCH_BASE=ou=groups,dc=example,dc=test
# COLLAB_LDAP_BIND_DN=
${ldapBindSecretLine()}
${ldapAdCompatibilityComments()}
COLLAB_GROUP_ROLE_MAP=cn=viewers,ou=groups,dc=example,dc=test=viewer;cn=contributors,ou=groups,dc=example,dc=test=contributor;cn=admins,ou=groups,dc=example,dc=test=admin

# COLLAB_BRIDGE_BIN=
# COLLAB_LIVE_PROFILE_CATALOG=
# COLLAB_PROFILE_CATALOG=
# COLLAB_LIVE_PROFILES=
# COLLAB_LIVE_VERCEL=0

${s3EvidenceComments()}`;
}

function renderLdap(): string {
  return `${HEADER}# Profile: encrypted LDAP deployment shape (directory is not contacted by doctor)
COLLAB_HOST=127.0.0.1
COLLAB_PORT=8787
COLLAB_SERVICE_NAME=cd-collab
COLLAB_EVIDENCE_ROOT=.data/evidence
COLLAB_COOKIE_SECURE=1
COLLAB_STORAGE=postgres
COLLAB_AUTH_MODE=ldap
COLLAB_STATIC_DIR=web/dist

# secret-store-sourced — placeholders, not a live connectivity claim
COLLAB_DATABASE_URL=postgres://collab_app:replace-from-secret-store@127.0.0.1:5432/collab
COLLAB_MIGRATE_DATABASE_URL=postgres://collab_migrator:replace-from-secret-store@127.0.0.1:5432/collab

COLLAB_LDAP_URL=ldaps://directory.example.test:636
COLLAB_LDAP_USER_DN_TEMPLATE=uid={username},ou=people,dc=example,dc=test
COLLAB_LDAP_GROUP_SEARCH_BASE=ou=groups,dc=example,dc=test
# COLLAB_LDAP_BIND_DN=
${ldapBindSecretLine()}
${ldapAdCompatibilityComments()}
COLLAB_GROUP_ROLE_MAP=cn=viewers,ou=groups,dc=example,dc=test=viewer;cn=contributors,ou=groups,dc=example,dc=test=contributor;cn=admins,ou=groups,dc=example,dc=test=admin

# COLLAB_BRIDGE_BIN=
# COLLAB_LIVE_PROFILE_CATALOG=
# COLLAB_PROFILE_CATALOG=
# COLLAB_LIVE_PROFILES=
# COLLAB_LIVE_VERCEL=0

${s3EvidenceComments()}`;
}

export function renderConfigFile(profile: ConfigInitProfile): string {
  switch (profile) {
    case "demo":
      return renderDemo();
    case "postgres":
      return renderPostgres();
    case "ldap":
      return renderLdap();
  }
}

function evidenceRootFrom(body: string): string {
  const match = body.match(/^COLLAB_EVIDENCE_ROOT=(.+)$/m);
  return (match?.[1] ?? ".data/evidence").trim();
}

async function exists(path: string): Promise<boolean> {
  try {
    await stat(path);
    return true;
  } catch {
    return false;
  }
}

async function assertWritableDirectory(path: string): Promise<void> {
  const probe = join(
    path,
    `.contextdesk-write-${process.pid}-${randomBytes(6).toString("hex")}.tmp`,
  );
  let handle: Awaited<ReturnType<typeof open>> | undefined;
  let created = false;
  let usable = true;
  try {
    handle = await open(probe, "wx", 0o600);
    created = true;
    await handle.writeFile("contextdesk operator write probe\n", "utf8");
    await handle.sync();
  } catch {
    usable = false;
  } finally {
    if (handle) {
      try {
        await handle.close();
      } catch {
        usable = false;
      }
    }
    if (created) {
      try {
        await unlink(probe);
      } catch {
        usable = false;
      }
    }
  }
  if (!usable) throw new Error("evidence root is not writable");
}

export async function initConfig(input: ConfigInitInput): Promise<ConfigInitResult> {
  const profile = input.profile ?? "demo";
  if (!isProfile(profile)) {
    throw new Error("config:init profile must be demo, postgres, or ldap");
  }
  const cwd = input.cwd ?? process.cwd();
  const example = join(input.collabRoot, ".env.example");
  if (!(await exists(example))) {
    throw new Error("collab .env.example is missing");
  }
  await readFile(example, "utf8");
  const outputPath = isAbsolute(input.output) ? input.output : resolve(cwd, input.output);
  const already = await exists(outputPath);
  if (already && !input.force) {
    if (input.nonInteractive || !input.confirmOverwrite) {
      throw new Error("refusing to overwrite existing file; pass --force");
    }
    const confirmed = await input.confirmOverwrite();
    if (!confirmed) throw new Error("config:init cancelled");
  }
  const body = renderConfigFile(profile);
  const evidence = evidenceRootFrom(body);
  const evidencePath = isAbsolute(evidence) ? evidence : resolve(cwd, evidence);
  await mkdir(dirname(outputPath), { recursive: true });
  await mkdir(evidencePath, { recursive: true });
  await assertWritableDirectory(evidencePath);
  await writeFile(outputPath, body, { encoding: "utf8", flag: "w", mode: 0o600 });
  // writeFile's mode only applies on creation; forced overwrites must also
  // tighten an existing environment file. Windows ACLs do not expose POSIX
  // mode semantics, so the successful exclusive write is the qualification.
  if (process.platform !== "win32") await chmod(outputPath, 0o600);
  return {
    outputPath,
    profile,
    createdDirectories: [evidencePath],
    overwritten: already,
  };
}
