import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";
import {
  parseCompiledTriagePolicyV2,
  parseTriageCancellationV1,
  parseTriageReplayV1,
  parseTriageRequestV2,
} from "./triageSdkV2";

const fixtureDir = join(
  dirname(fileURLToPath(import.meta.url)),
  "..", "..", "..", "fixtures", "triage-sdk", "v2",
);

const load = (name: string): unknown =>
  JSON.parse(readFileSync(join(fixtureDir, name), "utf8"));

describe("Rust-generated triage SDK v2 contracts", () => {
  it("accepts the exact request and ordered replay goldens", () => {
    expect(parseTriageRequestV2(load("request.standard.json")).run_id).toBe("run:golden:01");
    expect(parseTriageReplayV1(load("replay.partial.json")).events).toHaveLength(6);
    expect(parseTriageReplayV1(load("replay.cancelled-partial.json")).events).toHaveLength(5);
    expect(parseCompiledTriagePolicyV2(load("policy-preflight.standard.json")).slots).toHaveLength(1);
    expect(parseTriageCancellationV1(load("cancellation.json")).run_id).toBe("run:golden:01");
  });

  it("accepts the production-ledger completed replay golden", () => {
    // Generated by the Rust production event ledger
    // (cd-workflow/tests/triage_policy_run_ledger.rs), not the mock runner:
    // run_started, packet_ready, two role attempts, reconciliation,
    // validation, and one completed terminal carrying the grounded result.
    const replay = parseTriageReplayV1(load("replay.production-contributors.json"));
    expect(replay.events).toHaveLength(7);
    expect(replay.run_id).toBe("run-fixture-1");
    const terminal = replay.events[replay.events.length - 1] as {
      event: { kind: string; result?: { kind: string; validation_state: string } };
    };
    expect(terminal.event.kind).toBe("completed");
    expect(terminal.event.result?.kind).toBe("grounded_final");
    expect(terminal.event.result?.validation_state).toBe("passed");
  });

  it.each([
    "request.unknown-version.invalid.json",
    "replay.bad-order.invalid.json",
    "replay.after-terminal.invalid.json",
  ])("rejects %s", (name) => {
    const parse = name.startsWith("request.")
      ? parseTriageRequestV2
      : parseTriageReplayV1;
    expect(() => parse(load(name))).toThrow();
  });

  it("rejects unknown event fields and kinds", () => {
    const replay = load("replay.partial.json") as { events: Record<string, unknown>[] };
    (replay.events[0].event as Record<string, unknown>).provider_body = "forbidden";
    expect(() => parseTriageReplayV1(replay)).toThrow();
    (replay.events[0].event as Record<string, unknown>).kind = "future_kind";
    expect(() => parseTriageReplayV1(replay)).toThrow();
  });

  it("rejects oversized requests, identity sets, and replay streams", () => {
    const request = load("request.standard.json") as Record<string, unknown>;
    request.task = "x".repeat(64 * 1024 + 1);
    expect(() => parseTriageRequestV2(request)).toThrow();

    const tooManySources = load("request.standard.json") as Record<string, unknown>;
    (tooManySources.scope as Record<string, unknown>).source_ids = Array.from(
      { length: 257 },
      (_, index) => `source:${index}`,
    );
    expect(() => parseTriageRequestV2(tooManySources)).toThrow();

    const replay = load("replay.partial.json") as Record<string, unknown>;
    replay.events = Array.from({ length: 4097 }, (_, index) => ({
      schema_id: "contextdesk.triage.run_event.v2",
      run_id: "run:golden:01",
      sequence: index,
      privacy: "owner_only",
      event: { kind: "validation", passed: false },
    }));
    expect(() => parseTriageReplayV1(replay)).toThrow();
  });

  it("rejects non-exact inline-policy schemas and excessive overrides", () => {
    const request = load("request.standard.json") as Record<string, unknown>;
    request.policy = {
      kind: "inline",
      schema_id: "contextdesk.triage_policy.v999",
      document: {
        schema_id: "contextdesk.triage_policy.v999",
        mode: "standard",
      },
    };
    expect(() => parseTriageRequestV2(request)).toThrow();

    const override = load("request.standard.json") as Record<string, unknown>;
    override.overrides = { deadline_ms: 3_600_001, max_provider_calls: 65 };
    expect(() => parseTriageRequestV2(override)).toThrow();
  });

  it("keeps ModelRef profile bounds in parity with Rust", () => {
    const compiled = load("policy-preflight.standard.json") as {
      slots: Array<{ model: { profile_id: string } }>;
    };
    compiled.slots[0].model.profile_id = "p".repeat(257);
    expect(() => parseCompiledTriagePolicyV2(compiled)).toThrow();
  });
});
