/**
 * Renders the reviewed scenario matrix from the catalog.
 *
 * The matrix is generated rather than hand-maintained so the document and the
 * executable journeys cannot drift apart. `npm run scenarios:matrix -w
 * @cd-collab/e2e` writes it; `--check` fails when the committed file is stale.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { WAR_ROOM_SCENARIOS } from "./scenarios.js";
import { catalogProblems } from "./acceptance.js";

const here = dirname(fileURLToPath(import.meta.url));
export const MATRIX_PATH = join(here, "..", "..", "..", "..", "docs", "WAR_ROOM_SCENARIO_MATRIX.md");

const GENERATED_NOTE =
  "<!-- Generated by `npm run scenarios:matrix -w @cd-collab/e2e` from "
  + "collab/e2e/src/war-room/scenarios.ts. Edit the catalog, not this file. -->";

function cell(value: string): string {
  return value.replace(/\|/g, "\\|");
}

function bullets(values: readonly string[]): string {
  return values.map((value) => `- ${value}`).join("\n");
}

export function renderMatrix(): string {
  const lines: string[] = [];
  lines.push("# War Room scenario matrix");
  lines.push("");
  lines.push(GENERATED_NOTE);
  lines.push("");
  lines.push(
    "Deterministic, offline journeys used for repeated Computer Use acceptance of the",
    "ContextDesk War Room. Every fixture is synthetic and authored in-tree; no journey",
    "asserts that a model was correct, fast, or better than another, and none asserts a",
    "provider usage or cost figure, because the product reports those as unknown.",
  );
  lines.push("");
  lines.push("Run them with:");
  lines.push("");
  lines.push("```sh");
  lines.push("cd collab");
  lines.push("npm run build -w @cd-collab/contracts && npm run build -w @cd-collab/web");
  lines.push("npm run test -w @cd-collab/e2e -- specs/19-war-room-intake.spec.ts \\");
  lines.push("  specs/20-war-room-collaboration.spec.ts \\");
  lines.push("  specs/21-war-room-lanes-and-deployment.spec.ts \\");
  lines.push("  specs/22-war-room-a11y-responsive.spec.ts");
  lines.push("```");
  lines.push("");
  lines.push(
    "Each journey writes `collab/e2e/test-results/war-room-acceptance/<scenario>.json`",
    "recording every declared assertion, what the run observed, and the deep links it",
    "opened. A journey that never reaches a declared assertion fails rather than",
    "passing quietly.",
  );
  lines.push("");
  lines.push("## Matrix");
  lines.push("");
  lines.push("| # | Scenario | Triage question | Assertions | Spec | Requires |");
  lines.push("| --- | --- | --- | --- | --- | --- |");
  for (const row of [...WAR_ROOM_SCENARIOS].sort((a, b) => a.ordinal - b.ordinal)) {
    lines.push(
      `| ${row.ordinal} | ${cell(row.title)} | ${cell(row.triageQuestion)} | ${row.assertions.length} `
        + `| \`${row.spec}\` | ${row.requires ? `\`${row.requires}\`` : "default fixture server"} |`,
    );
  }
  lines.push("");
  lines.push("## Journeys");
  lines.push("");
  for (const row of [...WAR_ROOM_SCENARIOS].sort((a, b) => a.ordinal - b.ordinal)) {
    lines.push(`### ${row.ordinal}. ${row.title}`);
    lines.push("");
    lines.push(`**Triage question.** ${row.triageQuestion}`);
    lines.push("");
    lines.push("**Expected evidence visible to humans**");
    lines.push("");
    lines.push(bullets(row.expectedEvidence));
    lines.push("");
    lines.push("**Expected provenance**");
    lines.push("");
    lines.push(bullets(row.expectedProvenance));
    lines.push("");
    lines.push("**Stays unknown**");
    lines.push("");
    lines.push(bullets(row.expectedUnknowns));
    lines.push("");
    lines.push("**Useful next actions**");
    lines.push("");
    lines.push(bullets(row.usefulNextActions));
    lines.push("");
    lines.push("**Deep-link targets**");
    lines.push("");
    lines.push("| Target | Purpose | Address |");
    lines.push("| --- | --- | --- |");
    for (const link of row.deepLinks) {
      lines.push(`| \`${link.id}\` | ${cell(link.purpose)} | \`${cell(link.template)}\` |`);
    }
    lines.push("");
    lines.push("**Pass/fail usability assertions**");
    lines.push("");
    lines.push("| Assertion | Passes when | Fails when |");
    lines.push("| --- | --- | --- |");
    for (const item of row.assertions) {
      lines.push(`| \`${item.id}\` | ${cell(item.claim)} | ${cell(item.failsWhen)} |`);
    }
    lines.push("");
  }
  return `${lines.join("\n").replace(/\n{3,}/g, "\n\n").trimEnd()}\n`;
}

function main(): void {
  const problems = catalogProblems();
  if (problems.length > 0) {
    process.stderr.write(`War Room scenario catalog is invalid:\n- ${problems.join("\n- ")}\n`);
    process.exitCode = 1;
    return;
  }
  const rendered = renderMatrix();
  if (process.argv.includes("--check")) {
    let current = "";
    try {
      current = readFileSync(MATRIX_PATH, "utf8");
    } catch {
      process.stderr.write(`missing ${MATRIX_PATH}; run: npm run scenarios:matrix -w @cd-collab/e2e\n`);
      process.exitCode = 1;
      return;
    }
    if (current !== rendered) {
      process.stderr.write(
        `${MATRIX_PATH} is stale; run: npm run scenarios:matrix -w @cd-collab/e2e\n`,
      );
      process.exitCode = 1;
      return;
    }
    process.stdout.write(`War Room scenario matrix is current (${WAR_ROOM_SCENARIOS.length} scenarios).\n`);
    return;
  }
  writeFileSync(MATRIX_PATH, rendered, "utf8");
  process.stdout.write(`wrote ${MATRIX_PATH} (${WAR_ROOM_SCENARIOS.length} scenarios)\n`);
}

if (process.argv[1] && import.meta.url === `file://${process.argv[1]}`) {
  main();
}
