#!/usr/bin/env bash

set -euo pipefail
IFS=$'\n\t'

SCRIPT_UNDER_TEST="$(cd "$(dirname "$0")/.." && pwd -P)/local-build-cache.sh"
readonly SCRIPT_UNDER_TEST
TEMP_PARENT="${TMPDIR:-/tmp}"
TEMP_PARENT="${TEMP_PARENT%/}"
TEST_ROOT="$(mktemp -d "$TEMP_PARENT/contextdesk-cache-test.XXXXXX")"
TEST_ROOT="$(cd "$TEST_ROOT" && pwd -P)"
trap 'rm -rf "$TEST_ROOT"' EXIT

fail() {
  printf 'FAIL: %s\n' "$*" >&2
  exit 1
}

assert_contains() {
  local haystack="$1"
  local needle="$2"
  [[ "$haystack" == *"$needle"* ]] ||
    fail "expected output to contain: $needle"
}

assert_file_contents() {
  local path="$1"
  local expected="$2"
  [[ -f "$path" ]] || fail "missing file: $path"
  [[ "$(cat "$path")" == "$expected" ]] ||
    fail "unexpected contents in: $path"
}

expect_failure() {
  local expected="$1"
  shift
  local output
  if output="$("$@" 2>&1)"; then
    fail "command unexpectedly succeeded: $*"
  fi
  assert_contains "$output" "$expected"
}

make_repo_with_worktree() {
  local root="$1"
  local primary="$root/primary repo"
  local linked="$root/linked worktree"
  mkdir -p "$primary"
  git -C "$primary" init -q
  git -C "$primary" config user.email "cache-test@example.invalid"
  git -C "$primary" config user.name "Cache Test"
  cat >"$primary/Cargo.toml" <<'EOF'
[package]
name = "cache-test"
version = "0.0.0"
edition = "2021"
EOF
  mkdir -p "$primary/src"
  printf 'fn main() {}\n' >"$primary/src/main.rs"
  git -C "$primary" add Cargo.toml src/main.rs
  git -C "$primary" commit -qm "initial"
  git -C "$primary" worktree add -q -b linked "$linked"
  printf '%s\n%s\n' "$primary" "$linked"
}

mark_target() {
  local target="$1"
  mkdir -p "$target/debug"
  cat >"$target/CACHEDIR.TAG" <<'EOF'
Signature: 8a477f597d28d172789f06886806bc55d
EOF
}

printf '1..9\n'

WORKTREE_LIST="$(make_repo_with_worktree "$TEST_ROOT/reuse")"
PRIMARY="${WORKTREE_LIST%%$'\n'*}"
LINKED="${WORKTREE_LIST#*$'\n'}"
CACHE_ROOT="$TEST_ROOT/shared cache"

activation_one="$(cd "$PRIMARY" && "$SCRIPT_UNDER_TEST" activate --cache-root "$CACHE_ROOT")"
mkdir -p "$LINKED/desktop/src-tauri"
activation_two="$(cd "$LINKED/desktop/src-tauri" && \
  "$SCRIPT_UNDER_TEST" activate --cache-root "$CACHE_ROOT")"
PRIMARY_CACHE_TARGET="$(printf '%s\n' "$activation_one" | sed -n "s/^export CARGO_TARGET_DIR='\(.*\)'$/\1/p")"
LINKED_CACHE_TARGET="$(printf '%s\n' "$activation_two" | sed -n "s/^export CARGO_TARGET_DIR='\(.*\)'$/\1/p")"
[[ -n "$PRIMARY_CACHE_TARGET" && -n "$LINKED_CACHE_TARGET" ]] ||
  fail "activation did not export scoped targets"
[[ "$PRIMARY_CACHE_TARGET" != "$LINKED_CACHE_TARGET" ]] ||
  fail "different worktrees unsafely resolved the same target"
[[ "$PRIMARY_CACHE_TARGET" == "$CACHE_ROOT/cargo-targets/"* ]] ||
  fail "primary target was not cache-root scoped"
[[ "$LINKED_CACHE_TARGET" == "$CACHE_ROOT/cargo-targets/"* ]] ||
  fail "linked target was not cache-root scoped"
[[ -f "$PRIMARY_CACHE_TARGET/.contextdesk-generated-target-v1" &&
  -f "$PRIMARY_CACHE_TARGET/.contextdesk-worktree-scope-v2" &&
  -f "$LINKED_CACHE_TARGET/.contextdesk-generated-target-v1" &&
  -f "$LINKED_CACHE_TARGET/.contextdesk-worktree-scope-v2" ]] ||
  fail "worktree target markers missing"
scoped_dry_run="$($SCRIPT_UNDER_TEST cleanup --dry-run \
  --repo-root "$LINKED" --cache-root "$CACHE_ROOT" --target "$LINKED_CACHE_TARGET")"
assert_contains "$scoped_dry_run" "WOULD_CLEAN kind=worktree-scoped"
printf 'ok 1 - different worktrees resolve isolated cache targets\n'

PRIMARY_TARGET="$PRIMARY/target"
mark_target "$PRIMARY_TARGET"
expect_failure "primary checkout" "$SCRIPT_UNDER_TEST" cleanup --dry-run \
  --repo-root "$LINKED" --cache-root "$CACHE_ROOT" --target "$PRIMARY_TARGET"
printf 'ok 2 - primary checkout target is refused\n'

expect_failure "directory does not exist" "$SCRIPT_UNDER_TEST" cleanup --dry-run \
  --repo-root "$LINKED" --cache-root "$CACHE_ROOT" --target "$LINKED/missing target"
printf 'ok 3 - missing targets are refused\n'

LINKED_TARGET="$LINKED/target"
mark_target "$LINKED_TARGET"
SYMLINK_PARENT="$TEST_ROOT/symlink-parent"
ln -s "$LINKED" "$SYMLINK_PARENT"
expect_failure "symlink path components" "$SCRIPT_UNDER_TEST" cleanup --dry-run \
  --repo-root "$LINKED" --cache-root "$CACHE_ROOT" --target "$SYMLINK_PARENT/target"
expect_failure "not an exact registered Cargo target" "$SCRIPT_UNDER_TEST" cleanup --dry-run \
  --repo-root "$LINKED" --cache-root "$CACHE_ROOT" --target "$LINKED"
INSIDE_WORKTREE_CACHE="$LINKED/unsafe shared cache"
(cd "$LINKED" && expect_failure "outside every registered worktree" \
  "$SCRIPT_UNDER_TEST" activate --cache-root "$INSIDE_WORKTREE_CACHE")
[[ ! -e "$INSIDE_WORKTREE_CACHE" ]] ||
  fail "refused activation created a directory inside the worktree"
printf 'ok 4 - symlink escapes and workspace roots are refused\n'

printf 'tracked\n' >"$LINKED/tracked.txt"
git -C "$LINKED" add tracked.txt
git -C "$LINKED" commit -qm "tracked fixture"
printf 'untracked\n' >"$LINKED/untracked note.txt"
printf 'generated bytes\n' >"$LINKED_TARGET/debug/generated.bin"
dry_run_output="$("$SCRIPT_UNDER_TEST" cleanup --dry-run \
  --repo-root "$LINKED" --cache-root "$CACHE_ROOT" --target "$LINKED_TARGET")"
assert_contains "$dry_run_output" "WOULD_CLEAN"
[[ -f "$LINKED_TARGET/debug/generated.bin" ]] || fail "dry run changed target"
printf 'ok 5 - cleanup dry run is descriptive and non-mutating\n'

inventory_output="$("$SCRIPT_UNDER_TEST" inventory \
  --repo-root "$LINKED" --cache-root "$CACHE_ROOT")"
assert_contains "$inventory_output" "INVENTORY mode=dry-run"
assert_contains "$inventory_output" "WORKTREE role=primary active=registered"
assert_contains "$inventory_output" "WORKTREE role=linked active=registered dirty=yes"
assert_contains "$inventory_output" "TARGET kind=root safe_to_regenerate=yes"
assert_contains "$inventory_output" "TARGET kind=worktree-scoped safe_to_regenerate=yes"
printf 'ok 6 - inventory distinguishes worktrees, dirt, and generated targets\n'

tracked_before="$(shasum -a 256 "$LINKED/tracked.txt" | awk '{print $1}')"
untracked_before="$(shasum -a 256 "$LINKED/untracked note.txt" | awk '{print $1}')"
apply_output="$("$SCRIPT_UNDER_TEST" cleanup --apply \
  --repo-root "$LINKED" --cache-root "$CACHE_ROOT" --target "$LINKED_TARGET" 2>&1)"
assert_contains "$apply_output" "CLEANED"
[[ ! -e "$LINKED_TARGET/debug/generated.bin" ]] || fail "generated bytes were not reclaimed"
[[ "$(shasum -a 256 "$LINKED/tracked.txt" | awk '{print $1}')" == "$tracked_before" ]] ||
  fail "tracked source changed"
[[ "$(shasum -a 256 "$LINKED/untracked note.txt" | awk '{print $1}')" == "$untracked_before" ]] ||
  fail "untracked source changed"
printf 'ok 7 - apply reclaims only generated target bytes\n'

mark_target "$LINKED_TARGET"
APP_SOURCE="$LINKED_TARGET/release/bundle/macos/ContextDesk Test.app"
mkdir -p "$APP_SOURCE/Contents/MacOS"
printf 'exact package\n' >"$APP_SOURCE/Contents/MacOS/ContextDesk"
expect_failure "no verified preserved copy" "$SCRIPT_UNDER_TEST" cleanup --dry-run \
  --repo-root "$LINKED" --cache-root "$CACHE_ROOT" --target "$LINKED_TARGET"
APP_COPY="$TEST_ROOT/preserved packages/commit-123/ContextDesk Test.app"
preserve_output="$(cd "$LINKED" && "$SCRIPT_UNDER_TEST" preserve-app \
  --source "$APP_SOURCE" --destination "$APP_COPY")"
assert_contains "$preserve_output" "PRESERVED_APP"
package_cleanup="$("$SCRIPT_UNDER_TEST" cleanup --apply \
  --repo-root "$LINKED" --cache-root "$CACHE_ROOT" \
  --preserved-app "$APP_COPY" --target "$LINKED_TARGET" 2>&1)"
assert_contains "$package_cleanup" "CLEANED"
assert_file_contents "$APP_COPY/Contents/MacOS/ContextDesk" "exact package"
printf 'ok 8 - package must be preserved and verified before cleanup\n'

mark_target "$LINKED_TARGET"
mkdir -p "$LINKED_TARGET/release"
ln -s "$TEST_ROOT" "$LINKED_TARGET/release/Bad.app"
expect_failure "symlinked packaged apps" "$SCRIPT_UNDER_TEST" cleanup --dry-run \
  --repo-root "$LINKED" --cache-root "$CACHE_ROOT" --target "$LINKED_TARGET"
printf 'ok 9 - symlinked app bundles are refused\n'
