/**
 * Expandable diagnostics + redacted GitHub issue helpers (#325 P0–P1).
 * Never put secrets or full corp hostnames into clipboard/issue bodies.
 */

const TOKEN_RE =
  /\b(sk-[a-zA-Z0-9_-]{8,}|xai-[a-zA-Z0-9_-]{8,}|ghp_[a-zA-Z0-9]{20,}|gho_[a-zA-Z0-9]{20,}|github_pat_[a-zA-Z0-9_]{20,}|Bearer\s+[A-Za-z0-9\-._~+/]+=*)\b/gi;

/** Host labels that look private/corp (not public SaaS). */
const CORP_HOST_RE =
  /\b(?:[a-z0-9-]+\.)*(?:internal|corp|intranet|local|lan|private|ies)\.[a-z0-9.-]+\b/gi;

export type DiagnosticReport = {
  /** One-line human summary. */
  summary: string;
  /** Expandable technical detail (already redacted). */
  technical: string;
  /** Full markdown body for clipboard / GitHub (redacted). */
  reportMarkdown: string;
  /** Prefilled new-issue URL (may truncate body if very long). */
  githubNewIssueUrl: string;
};

/** Strip secrets, bearer tokens, query strings, and corp-looking hostnames. */
export function redactDiagnosticText(raw: string): string {
  let s = raw;
  s = s.replace(TOKEN_RE, "[REDACTED_TOKEN]");
  // Drop query strings on URLs (CQL, secrets in params).
  s = s.replace(/(https?:\/\/[^?\s]+)\?[^\s)\]"']*/gi, "$1?[REDACTED_QUERY]");
  s = s.replace(CORP_HOST_RE, "[REDACTED-HOST]");
  // Private IPv4 / CGNAT
  s = s.replace(
    /\b(?:10\.\d{1,3}\.\d{1,3}\.\d{1,3}|192\.168\.\d{1,3}\.\d{1,3}|172\.(?:1[6-9]|2\d|3[0-1])\.\d{1,3}\.\d{1,3}|100\.(?:6[4-9]|[7-9]\d|1[0-1]\d|12[0-7])\.\d{1,3}\.\d{1,3})\b/g,
    "[REDACTED-IP]",
  );
  return s;
}

function summarizeError(raw: string): string {
  const r = raw.trim();
  if (!r) return "Unknown error";
  // Prefer first line / short prefix
  const line = r.split("\n")[0] ?? r;
  return line.length > 160 ? `${line.slice(0, 157)}…` : line;
}

/** Build a diagnostic package from a raw error string (host/agent message). */
export function buildErrorReport(args: {
  raw: string;
  appVersion?: string;
  /** `dev` | `installed` (#338). */
  channel?: string;
  gitSha?: string;
  identityLine?: string;
  osHint?: string;
  owner?: string;
  repo?: string;
}): DiagnosticReport {
  const redacted = redactDiagnosticText(args.raw);
  const summary = summarizeError(redacted);
  const technical = redacted;
  const version = args.appVersion?.trim() || "unknown";
  const channel = args.channel?.trim() || "unknown";
  const git = args.gitSha?.trim();
  const identity =
    args.identityLine?.trim() ||
    [
      `v${version}`,
      `channel=${channel}`,
      git ? `git=${git}` : null,
    ]
      .filter(Boolean)
      .join(" · ");
  const os = args.osHint?.trim() || guessOs();
  const reportMarkdown = [
    "## Summary",
    summary,
    "",
    "## Technical details (redacted)",
    "```",
    technical,
    "```",
    "",
    "## Environment",
    `- App: ${version}`,
    `- Channel: ${channel}`,
    ...(git ? [`- Git: ${git}`] : []),
    `- Identity: ${identity}`,
    `- OS: ${os}`,
    "",
    "_Generated by ContextDesk. Secrets and private hosts are redacted. Do not paste tokens into issues._",
  ].join("\n");

  const owner = args.owner ?? "chriscase";
  const repo = args.repo ?? "ContextDesk";
  const title = `[bug] ${summary}`.slice(0, 120);
  const githubNewIssueUrl = buildGitHubNewIssueUrl({
    owner,
    repo,
    title,
    body: reportMarkdown,
  });

  return {
    summary,
    technical,
    reportMarkdown,
    githubNewIssueUrl,
  };
}

/** Open `github.com/.../issues/new` with title/body (browser length limits apply). */
export function buildGitHubNewIssueUrl(args: {
  owner: string;
  repo: string;
  title: string;
  body: string;
  labels?: string[];
}): string {
  const base = `https://github.com/${encodeURIComponent(args.owner)}/${encodeURIComponent(args.repo)}/issues/new`;
  const params = new URLSearchParams();
  params.set("title", args.title);
  // Keep body under ~6k chars for URL safety
  const body =
    args.body.length > 6000
      ? `${args.body.slice(0, 5900)}\n\n…(truncated for URL length)`
      : args.body;
  params.set("body", body);
  if (args.labels?.length) {
    params.set("labels", args.labels.join(","));
  }
  return `${base}?${params.toString()}`;
}

function guessOs(): string {
  if (typeof navigator === "undefined") return "unknown";
  const ua = navigator.userAgent || "";
  if (/Mac/i.test(ua)) return "macOS";
  if (/Win/i.test(ua)) return "Windows";
  if (/Linux/i.test(ua)) return "Linux";
  return "unknown";
}
