//! Retrieval-ablation benchmark lab: deterministic hidden-truth corpus
//! generation, host-neutral mode contract, and versioned manifests.
//!
//! Included as a child of `log_lab_generator.rs` (exactly like
//! `log_lab_behavior.rs`) so it reuses the frozen Log Lab helpers
//! (`verify_safety`, `tree_hashes`, `json_line`, `logfmt`, deterministic ZIP)
//! instead of creating a parallel fixture system.
//!
//! Committed layout under `fixtures/log-lab/`:
//!
//! ```text
//! schema/retrieval-*.v1.schema.json          versioned contract documents
//! scenarios/retrieval-ablation/suite.json    suite manifest
//! scenarios/retrieval-ablation/cases/<id>/
//!     import/       model-visible logs (the ONLY import root)
//!     queries.json  harness input (model-safe questions + keyword plans)
//!     truth/        evaluator-only manifest (never import, never attach)
//! ```
//!
//! Evaluator truth references model-visible events by unique opaque message
//! token resolved to `(seq, source)` at scoring time — the same convention as
//! `fixtures/triage-root-cause-lab/`. Truth-only identifiers (`group_id`,
//! roles, gains) never appear under `import/`; isolation tests enforce this.

use serde::{Deserialize, Serialize};
use serde_json::{json, Value};
use std::collections::BTreeMap;
use std::fmt;

use super::LabResult;

#[path = "retrieval_ablation_cases.rs"]
mod retrieval_ablation_cases;
pub use retrieval_ablation_cases::*;

#[path = "retrieval_ablation_scoring.rs"]
mod retrieval_ablation_scoring;
pub use retrieval_ablation_scoring::*;

#[path = "retrieval_ablation_harness.rs"]
mod retrieval_ablation_harness;
pub use retrieval_ablation_harness::*;

// ---------------------------------------------------------------------------
// Suite identity and versioning
// ---------------------------------------------------------------------------

pub const RA_SUITE_ID: &str = "contextdesk.log_lab.retrieval_ablation";
pub const RA_SUITE_VERSION: u32 = 1;
pub const RA_GENERATOR_VERSION: &str = "contextdesk.log_lab.retrieval_ablation.generator.v1";
pub const RA_SUITE_SCHEMA_ID: &str = "contextdesk.log_lab.retrieval_suite.v1";
pub const RA_TRUTH_SCHEMA_ID: &str = "contextdesk.log_lab.retrieval_truth.v1";
pub const RA_TRUTH_SCHEMA_VERSION: u32 = 1;
pub const RA_QUERYSET_SCHEMA_ID: &str = "contextdesk.log_lab.retrieval_queries.v1";
pub const RA_QUERYSET_SCHEMA_VERSION: u32 = 1;
pub const RA_RUN_RECORD_SCHEMA_ID: &str = "contextdesk.log_lab.retrieval_run_record.v1";
pub const RA_RUN_RECORD_SCHEMA_VERSION: u32 = 1;
pub const RA_REPORT_SCHEMA_ID: &str = "contextdesk.log_lab.retrieval_report.v1";
pub const RA_REPORT_SCHEMA_VERSION: u32 = 1;

/// Default deterministic seed for the committed small tier. Overridable so
/// seed-variation tests can prove "different seed => different neutral
/// identities, same semantic truth".
pub const RA_DEFAULT_SEED: u64 = 92_026_080_701;

/// Fixed suite epoch: 2025-02-19T21:20:00Z. Far enough from any plausible
/// "now" that the frozen Log Lab safety scan never flags near-current epochs,
/// and distinct from the compact-lab epoch so cross-suite probes cannot
/// collide.
pub const RA_BASE_TS: i64 = 1_740_000_000;

/// Neutral timestamp jitter bound (seconds): the suite window may shift by up
/// to ±3 days with the seed, quantised to whole minutes. Ordering and
/// inter-event deltas are semantic and never change with the seed.
pub const RA_SEED_JITTER_BOUND_SECS: i64 = 259_200;

pub const RA_PROFILE: &str = "retrieval-ablation";
pub const RA_CASE_COUNT: usize = 20;

/// Noise multipliers per tier. Truth events are constant across tiers; only
/// neutral noise volume scales, so rarity gets harder as tiers grow. Some
/// cases cap their multiplier (`RaCaseSpec::scale_cap`) because their probe
/// is structural, not volumetric; the caps are disclosed in `suite.json`.
pub const RA_MEDIUM_NOISE_MULTIPLIER: u64 = 28;
pub const RA_LARGE_NOISE_MULTIPLIER: u64 = 124;

pub const RA_PROVENANCE: &str = "Entirely synthetic and generated by the ContextDesk repository; \
     no customer, employer, developer-machine, production, or third-party log material.";

pub const RA_EVALUATOR_ISOLATION_NOTE: &str = "Everything under truth/ is an answer key. Import \
     only the sibling import/ directory and never attach truth or queries to model context.";

// ---------------------------------------------------------------------------
// Tiers
// ---------------------------------------------------------------------------

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum RaTier {
    Small,
    Medium,
    Large,
}

impl RaTier {
    pub fn parse(value: &str) -> LabResult<Self> {
        match value {
            "small" => Ok(Self::Small),
            "medium" => Ok(Self::Medium),
            "large" => Ok(Self::Large),
            other => Err(format!("unsupported retrieval-ablation tier: {other}").into()),
        }
    }

    pub fn as_str(self) -> &'static str {
        match self {
            Self::Small => "small",
            Self::Medium => "medium",
            Self::Large => "large",
        }
    }

    pub fn noise_multiplier(self) -> u64 {
        match self {
            Self::Small => 1,
            Self::Medium => RA_MEDIUM_NOISE_MULTIPLIER,
            Self::Large => RA_LARGE_NOISE_MULTIPLIER,
        }
    }
}

impl fmt::Display for RaTier {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(self.as_str())
    }
}

// ---------------------------------------------------------------------------
// Deterministic RNG (neutral surface only)
// ---------------------------------------------------------------------------

/// SplitMix64: tiny, stable-forever PRNG implemented locally so determinism
/// never depends on an external crate's stream stability. It randomises the
/// NEUTRAL surface only (identifiers, epoch shift, filler values); semantic
/// structure is fixed by the case specifications.
#[derive(Debug, Clone)]
pub struct RaRng(u64);

impl RaRng {
    pub fn new(seed: u64) -> Self {
        Self(seed)
    }

    pub fn for_case(seed: u64, case_id: &str) -> Self {
        Self(seed ^ fnv1a64(case_id.as_bytes()))
    }

    pub fn next_u64(&mut self) -> u64 {
        self.0 = self.0.wrapping_add(0x9E37_79B9_7F4A_7C15);
        let mut z = self.0;
        z = (z ^ (z >> 30)).wrapping_mul(0xBF58_476D_1CE4_E5B9);
        z = (z ^ (z >> 27)).wrapping_mul(0x94D0_49BB_1331_11EB);
        z ^ (z >> 31)
    }

    pub fn next_range(&mut self, bound: u64) -> u64 {
        if bound == 0 {
            return 0;
        }
        self.next_u64() % bound
    }

    /// Eight lowercase hex characters; the workhorse for request/trace ids.
    pub fn hex8(&mut self) -> String {
        format!("{:08x}", self.next_u64() & 0xFFFF_FFFF)
    }

    /// Eight UPPERCASE hex characters. Evidence-group tokens use this so a
    /// token can never collide with (or contain) a lowercase noise id; the
    /// production search is case-insensitive, while scorer token matching is
    /// deliberately case-sensitive.
    pub fn hex8_upper(&mut self) -> String {
        format!("{:08X}", self.next_u64() & 0xFFFF_FFFF)
    }
}

pub fn fnv1a64(bytes: &[u8]) -> u64 {
    let mut hash: u64 = 0xCBF2_9CE4_8422_2325;
    for byte in bytes {
        hash ^= u64::from(*byte);
        hash = hash.wrapping_mul(0x0000_0100_0000_01B3);
    }
    hash
}

/// Suite epoch for a seed: `RA_BASE_TS` plus a minute-quantised jitter in
/// `[-RA_SEED_JITTER_BOUND_SECS, +RA_SEED_JITTER_BOUND_SECS]`.
pub fn ra_suite_epoch(seed: u64) -> i64 {
    let mut rng = RaRng::new(seed ^ 0x5245_5452_4945_5641);
    let window = (RA_SEED_JITTER_BOUND_SECS * 2 / 60) as u64 + 1;
    let offset_minutes = rng.next_range(window) as i64;
    RA_BASE_TS - RA_SEED_JITTER_BOUND_SECS + offset_minutes * 60
}

// ---------------------------------------------------------------------------
// Causal roles, modes, partition
// ---------------------------------------------------------------------------

#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum RaRole {
    Trigger,
    Propagation,
    Symptom,
    Recovery,
    Decoy,
    Neutral,
}

impl RaRole {
    pub fn as_str(self) -> &'static str {
        match self {
            Self::Trigger => "trigger",
            Self::Propagation => "propagation",
            Self::Symptom => "symptom",
            Self::Recovery => "recovery",
            Self::Decoy => "decoy",
            Self::Neutral => "neutral",
        }
    }

    /// Default nDCG gain for a role. Truth may override per query.
    pub fn default_gain(self) -> u8 {
        match self {
            Self::Trigger => 3,
            Self::Propagation => 2,
            Self::Symptom | Self::Recovery | Self::Neutral => 1,
            Self::Decoy => 0,
        }
    }
}

/// The host-neutral ablation modes. A mode that cannot run in the current
/// build/environment MUST surface as `FUTURE_CAPABILITY_UNAVAILABLE` — never
/// silently substitute another mode and never count it as passing.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum RaMode {
    StructuredKeyword,
    HybridEmbedding,
    HybridEmbeddingReranked,
    FullMultistage,
}

impl RaMode {
    pub const ALL: [RaMode; 4] = [
        RaMode::StructuredKeyword,
        RaMode::HybridEmbedding,
        RaMode::HybridEmbeddingReranked,
        RaMode::FullMultistage,
    ];

    pub fn as_str(self) -> &'static str {
        match self {
            Self::StructuredKeyword => "structured_keyword",
            Self::HybridEmbedding => "hybrid_embedding",
            Self::HybridEmbeddingReranked => "hybrid_embedding_reranked",
            Self::FullMultistage => "full_multistage",
        }
    }

    pub fn parse(value: &str) -> LabResult<Self> {
        match value {
            "structured_keyword" => Ok(Self::StructuredKeyword),
            "hybrid_embedding" => Ok(Self::HybridEmbedding),
            "hybrid_embedding_reranked" => Ok(Self::HybridEmbeddingReranked),
            "full_multistage" => Ok(Self::FullMultistage),
            other => Err(format!("unsupported retrieval-ablation mode: {other}").into()),
        }
    }
}

impl fmt::Display for RaMode {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(self.as_str())
    }
}

/// Exactly one classification per (case, mode). Expected future improvements
/// are never encoded as forced pass conditions.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum RaPartition {
    #[serde(rename = "PASS_ON_BASE")]
    PassOnBase,
    #[serde(rename = "BASELINE_LIMITATION")]
    BaselineLimitation,
    #[serde(rename = "FUTURE_CAPABILITY_UNAVAILABLE")]
    FutureCapabilityUnavailable,
    #[serde(rename = "RED_REQUIRED_FIX")]
    RedRequiredFix,
}

impl RaPartition {
    pub fn as_str(self) -> &'static str {
        match self {
            Self::PassOnBase => "PASS_ON_BASE",
            Self::BaselineLimitation => "BASELINE_LIMITATION",
            Self::FutureCapabilityUnavailable => "FUTURE_CAPABILITY_UNAVAILABLE",
            Self::RedRequiredFix => "RED_REQUIRED_FIX",
        }
    }
}

impl fmt::Display for RaPartition {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(self.as_str())
    }
}

// ---------------------------------------------------------------------------
// Truth manifest (evaluator-only)
// ---------------------------------------------------------------------------

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct RaTruthManifest {
    pub schema_id: String,
    pub schema_version: u32,
    pub suite_id: String,
    pub suite_version: u32,
    pub case_id: String,
    pub case_version: u32,
    pub generator_version: String,
    pub seed: u64,
    pub tier: String,
    pub provenance: String,
    /// Guard flag mirrored from the company-shaped lab: any surface carrying
    /// this manifest into model context is a hard isolation failure.
    pub evaluator_only: bool,
    pub evaluator_isolation: String,
    pub intended_probe: String,
    pub title: String,
    pub base_ts: i64,
    pub expected: RaExpectedCorpus,
    pub incidents: Vec<RaIncident>,
    pub evidence_groups: Vec<RaEvidenceGroup>,
    pub known_counts: RaKnownCounts,
    pub required_claims: Vec<String>,
    pub forbidden_claims: Vec<String>,
    pub competing_explanations: Vec<String>,
    pub permitted_uncertainty: Vec<String>,
    pub privacy: RaPrivacy,
    pub retrieval_exclusions: Vec<RaExclusion>,
    pub per_query_relevance: BTreeMap<String, RaQueryTruth>,
    pub baseline_expectation: RaBaselineExpectation,
    /// Seed-invariant digest of the semantic skeleton (roles, counts,
    /// sources, relevance structure, claims). Two seeds must agree on it.
    pub semantic_truth_digest: String,
    /// Seed-dependent identity of the model-visible `import/` subtree.
    pub import_tree_sha256: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct RaExpectedCorpus {
    pub files: u64,
    /// Generator record count (one logical record may span multiple physical
    /// lines; excluded files contribute zero). The harness asserts the
    /// production importer agrees.
    pub events: u64,
    pub bytes: u64,
    pub source_count: u64,
    pub sources: BTreeMap<String, u64>,
    pub severities: BTreeMap<String, u64>,
    /// "wall" | "mixed" — coarse per-case time quality.
    pub time_quality: String,
    pub files_by_path: BTreeMap<String, RaFileFacts>,
    /// Files under import/ the production importer is expected to exclude
    /// (binary/unsupported); they carry zero expected events.
    pub excluded_files: Vec<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct RaFileFacts {
    pub sha256: String,
    pub bytes: u64,
    pub events: u64,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct RaIncident {
    pub incident_id: String,
    pub summary: String,
    /// "established" | "competing" | "unknown"
    pub root_cause_status: String,
    pub trigger_group_ids: Vec<String>,
    pub window_from_ts: i64,
    pub window_to_ts: i64,
}

/// One retrievable unit of evidence. A group may render as many raw records
/// (duplicate renderings); retrieving any rendering retrieves the group.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct RaEvidenceGroup {
    /// Evaluator-only identity; MUST NOT appear anywhere under `import/`.
    pub group_id: String,
    /// Unique model-visible token (substring match inside message text).
    pub token: String,
    pub sources: Vec<String>,
    pub role: RaRole,
    pub incident_id: Option<String>,
    /// Raw records carrying the token (lead renderings).
    pub expected_token_records: u64,
    /// All raw records belonging to the group including supporting stack /
    /// wrapped lines that do not carry the token.
    pub expected_raw_records: u64,
    pub expected_occurrences: u64,
    /// "wall" | "order_only" | "ambiguous_local" | "skewed"
    pub timestamp_certainty: String,
    pub ts: i64,
    pub notes: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct RaKnownCounts {
    /// "complete" | "partial_lower_bound"
    pub corpus_completeness: String,
    pub total_events_known: bool,
    /// Model-visible references to records absent from the corpus (e.g. a
    /// rotated-away segment). Zero means nothing is known-missing.
    pub known_missing_references: u64,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct RaPrivacy {
    /// Values that must never surface in retrieved context, run records, or
    /// reports. All carry the LOG-LAB-INVALID marker inside import bytes so
    /// they are unmistakably synthetic.
    pub secret_tokens: Vec<String>,
    pub marker: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct RaExclusion {
    pub token: String,
    pub reason: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct RaQueryTruth {
    pub answerable: bool,
    pub relevant: Vec<RaRelevantGroup>,
    /// Groups whose presence in top-k counts as decoy contamination for this
    /// query (decoys and unrelated-incident evidence).
    pub contaminating_groups: Vec<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct RaRelevantGroup {
    pub group_id: String,
    /// nDCG gain: trigger-grade evidence 3, propagation 2, symptom/recovery 1.
    pub gain: u8,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct RaBaselineExpectation {
    /// "pass" | "limitation" — what the CURRENT production structured/keyword
    /// baseline is expected to achieve on the small tier. This encodes
    /// observed reality as a regression floor; it never encodes hoped-for
    /// future capability.
    pub class: String,
    pub gates: RaBaselineGates,
    pub limitation_reason: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct RaBaselineGates {
    pub min_recall_at_25: Option<f64>,
    pub max_decoy_share_at_25: Option<f64>,
    /// Queries (by id) expected to stay below the recall floor under the
    /// baseline. Only meaningful when class == "limitation".
    pub queries_expected_below_floor: Vec<String>,
}

// ---------------------------------------------------------------------------
// Query sets (model-safe harness input)
// ---------------------------------------------------------------------------

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct RaQuerySet {
    pub schema_id: String,
    pub schema_version: u32,
    pub suite_id: String,
    pub case_id: String,
    pub queries: Vec<RaQuery>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct RaQuery {
    pub query_id: String,
    /// "broad" | "causal" | "symptom" | "identifier" | "negative" |
    /// "competing" | "chronology"
    pub kind: String,
    /// The natural question a user would ask. Embedding/multistage modes
    /// receive this text.
    pub question: String,
    /// Transparent, committed derivation for the structured/keyword baseline:
    /// content terms a reasonable user would type, plus structured filters
    /// only when the question itself implies them.
    pub keyword_plan: RaKeywordPlan,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct RaKeywordPlan {
    pub terms: Vec<String>,
    pub level: Option<String>,
    pub services: Vec<String>,
    pub sources: Vec<String>,
    pub time_from: Option<i64>,
    pub time_to: Option<i64>,
}

impl RaKeywordPlan {
    pub fn terms_only(terms: &[&str]) -> Self {
        Self {
            terms: terms.iter().map(|t| t.to_string()).collect(),
            level: None,
            services: Vec::new(),
            sources: Vec::new(),
            time_from: None,
            time_to: None,
        }
    }
}

// ---------------------------------------------------------------------------
// Run records (mode execution evidence)
// ---------------------------------------------------------------------------

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct RaRunRecord {
    pub schema_id: String,
    pub schema_version: u32,
    pub suite_id: String,
    pub suite_version: u32,
    pub case_id: String,
    pub tier_claimed: String,
    pub mode: RaMode,
    pub mode_status: RaModeStatus,
    pub engine: RaEngineManifest,
    pub corpus: RaCorpusStamp,
    pub calls: RaCallCounts,
    pub queries: Vec<RaQueryRun>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct RaModeStatus {
    /// "executed" | "unavailable"
    pub state: String,
    /// Required when state == "unavailable"; e.g. "not_implemented" or
    /// "requires_live_provider".
    pub unavailable_reason: Option<String>,
}

impl RaModeStatus {
    pub fn executed() -> Self {
        Self {
            state: "executed".into(),
            unavailable_reason: None,
        }
    }

    pub fn unavailable(reason: &str) -> Self {
        Self {
            state: "unavailable".into(),
            unavailable_reason: Some(reason.into()),
        }
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct RaEngineManifest {
    /// e.g. "cd-core.log_analysis.search_events_advanced"
    pub kind: String,
    /// Exact ContextDesk commit the engine was built from.
    pub contextdesk_sha: String,
    /// Ordering semantics disclosure, e.g. "chronological(ts,seq)".
    pub ranking: String,
    /// Model identity for embedding/reranking/LLM modes. `None` means "no
    /// model involved"; a mode that used a model MUST populate it (omitted is
    /// unknown, not zero — unknown blocks).
    pub model_identity: Option<String>,
    pub reranker_identity: Option<String>,
    pub deterministic: bool,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct RaCorpusStamp {
    pub tier_requested: String,
    pub seed: u64,
    pub generator_version: String,
    pub truth_schema_id: String,
    pub events_expected: u64,
    pub events_imported: u64,
    pub files: u64,
    pub bytes: u64,
    pub import_tree_sha256: String,
    pub generation_ms: Option<u64>,
    pub import_ms: Option<u64>,
}

/// Call/cost accounting. `None` = unknown (blocks when the mode claims to
/// have used the capability); `Some(0)` = measured zero.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct RaCallCounts {
    pub embedding_calls: Option<u64>,
    pub rerank_calls: Option<u64>,
    pub provider_calls: Option<u64>,
    pub tokens_in: Option<u64>,
    pub tokens_out: Option<u64>,
    pub cost_usd: Option<f64>,
}

impl RaCallCounts {
    pub fn measured_zero() -> Self {
        Self {
            embedding_calls: Some(0),
            rerank_calls: Some(0),
            provider_calls: Some(0),
            tokens_in: Some(0),
            tokens_out: Some(0),
            cost_usd: Some(0.0),
        }
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct RaQueryRun {
    pub query_id: String,
    pub k_requested: u64,
    /// Engine-reported total matches before truncation, when known.
    pub matched_total: Option<u64>,
    pub scanned: u64,
    pub partial: bool,
    pub runtime_ms: Option<u64>,
    pub candidates: Vec<RaCandidate>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct RaCandidate {
    /// 1-based position in the order the production engine presented it.
    pub rank: u64,
    /// Product event sequence identity within the imported corpus.
    pub seq: u64,
    pub source: String,
    pub ts: i64,
    pub timestamp_provenance: String,
    pub level: Option<String>,
    pub template_id: Option<u64>,
    pub score: Option<f64>,
    /// Exact message text as retrieved; scorers match truth tokens against
    /// this and derive supplied-context character counts from it.
    pub content: String,
}

// ---------------------------------------------------------------------------
// Suite manifest
// ---------------------------------------------------------------------------

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct RaSuiteManifest {
    pub schema_id: String,
    pub schema_version: u32,
    pub suite_id: String,
    pub suite_version: u32,
    pub generator_version: String,
    pub truth_schema_id: String,
    pub queryset_schema_id: String,
    pub seed: u64,
    pub tier: String,
    pub suite_epoch: i64,
    pub provenance: String,
    pub noise_multiplier: u64,
    pub cases: Vec<RaSuiteCaseEntry>,
    pub total_files: u64,
    pub total_events: u64,
    pub total_bytes: u64,
    /// SHA-256 over every committed byte of the suite subtree except this
    /// manifest itself (cases/**), in sorted relative-path order.
    pub corpus_identity_sha256: String,
    /// Seed-invariant digest across all cases' semantic digests.
    pub semantic_suite_digest: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct RaSuiteCaseEntry {
    pub case_id: String,
    pub case_version: u32,
    pub title: String,
    pub intended_probe: String,
    pub scale_cap: Option<u64>,
    pub files: u64,
    pub events: u64,
    pub bytes: u64,
    pub import_tree_sha256: String,
    pub semantic_truth_digest: String,
}

#[derive(Debug, Clone)]
pub struct RaSuiteSummary {
    pub tier: RaTier,
    pub seed: u64,
    pub cases: usize,
    pub files: u64,
    pub events: u64,
    pub bytes: u64,
    pub corpus_identity_sha256: String,
}

// ---------------------------------------------------------------------------
// Semantic digest
// ---------------------------------------------------------------------------

/// Canonical seed-invariant projection of a truth manifest. Excludes every
/// neutral-surface field (tokens, absolute timestamps, hashes, byte sizes)
/// and keeps the semantic skeleton. Used to prove "different seed => same
/// semantic truth".
pub fn ra_semantic_projection(truth: &RaTruthManifest) -> Value {
    let groups: Vec<Value> = truth
        .evidence_groups
        .iter()
        .map(|group| {
            json!({
                "group_id": group.group_id,
                "sources": group.sources,
                "role": group.role.as_str(),
                "incident_id": group.incident_id,
                "expected_token_records": group.expected_token_records,
                "expected_raw_records": group.expected_raw_records,
                "expected_occurrences": group.expected_occurrences,
                "timestamp_certainty": group.timestamp_certainty,
                "ts_rel": group.ts - truth.base_ts,
            })
        })
        .collect();
    let incidents: Vec<Value> = truth
        .incidents
        .iter()
        .map(|incident| {
            json!({
                "incident_id": incident.incident_id,
                "root_cause_status": incident.root_cause_status,
                "trigger_group_ids": incident.trigger_group_ids,
                "window_from_rel": incident.window_from_ts - truth.base_ts,
                "window_to_rel": incident.window_to_ts - truth.base_ts,
            })
        })
        .collect();
    let relevance: BTreeMap<&String, Value> = truth
        .per_query_relevance
        .iter()
        .map(|(query_id, entry)| {
            (
                query_id,
                json!({
                    "answerable": entry.answerable,
                    "relevant": entry.relevant.iter().map(|r| json!({
                        "group_id": r.group_id,
                        "gain": r.gain,
                    })).collect::<Vec<_>>(),
                    "contaminating_groups": entry.contaminating_groups,
                }),
            )
        })
        .collect();
    json!({
        "schema_id": truth.schema_id,
        "schema_version": truth.schema_version,
        "suite_id": truth.suite_id,
        "case_id": truth.case_id,
        "case_version": truth.case_version,
        "tier": truth.tier,
        "intended_probe": truth.intended_probe,
        "expected_events": truth.expected.events,
        "expected_sources": truth.expected.sources,
        "expected_severities": truth.expected.severities,
        "time_quality": truth.expected.time_quality,
        "excluded_files": truth.expected.excluded_files,
        "incidents": incidents,
        "evidence_groups": groups,
        "known_counts": {
            "corpus_completeness": truth.known_counts.corpus_completeness,
            "total_events_known": truth.known_counts.total_events_known,
            "known_missing_references": truth.known_counts.known_missing_references,
        },
        "required_claims": truth.required_claims,
        "forbidden_claims": truth.forbidden_claims,
        "competing_explanations": truth.competing_explanations,
        "permitted_uncertainty": truth.permitted_uncertainty,
        "secret_token_count": truth.privacy.secret_tokens.len(),
        "retrieval_exclusion_count": truth.retrieval_exclusions.len(),
        "per_query_relevance": relevance,
        "baseline_expectation": {
            "class": truth.baseline_expectation.class,
            "queries_expected_below_floor":
                truth.baseline_expectation.gates.queries_expected_below_floor,
        },
    })
}

pub fn ra_semantic_truth_digest(truth: &RaTruthManifest) -> LabResult<String> {
    let projection = ra_semantic_projection(truth);
    Ok(super::sha256_bytes(&serde_json::to_vec(&projection)?))
}

// ---------------------------------------------------------------------------
// Contract schema documents
// ---------------------------------------------------------------------------

/// Versioned JSON documents describing the four benchmark contracts. These
/// mirror the `deny_unknown_fields` serde structs above, which remain the
/// enforcing validators (repo convention: no jsonschema crate). Written into
/// `schema/` beside the frozen `truth.schema.json` and byte-frozen by the
/// regeneration test.
pub fn ra_schema_documents() -> Vec<(&'static str, Value)> {
    let truth = json!({
        "$id": format!("https://contextdesk.example/schemas/{RA_TRUTH_SCHEMA_ID}.json"),
        "title": "ContextDesk retrieval-ablation truth manifest",
        "schema_id": RA_TRUTH_SCHEMA_ID,
        "schema_version": RA_TRUTH_SCHEMA_VERSION,
        "authority": "crates/cd-core/tests/support/retrieval_ablation.rs::RaTruthManifest (serde, deny_unknown_fields)",
        "evaluator_only": true,
        "compatibility": {
            "relation_to_log_lab_truth_v1": "successor contract for retrieval benchmarking; log-lab truth.schema.json v1 remains frozen and unchanged",
            "event_reference": "unique message token resolved to (seq, source) at scoring time",
            "roles": ["trigger", "propagation", "symptom", "recovery", "decoy", "neutral"],
            "timestamp_certainty": ["wall", "order_only", "ambiguous_local", "skewed"],
            "corpus_completeness": ["complete", "partial_lower_bound"]
        },
        "required": [
            "schema_id", "schema_version", "suite_id", "suite_version", "case_id",
            "case_version", "generator_version", "seed", "tier", "provenance",
            "evaluator_only", "evaluator_isolation", "intended_probe", "title",
            "base_ts", "expected", "incidents", "evidence_groups", "known_counts",
            "required_claims", "forbidden_claims", "competing_explanations",
            "permitted_uncertainty", "privacy", "retrieval_exclusions",
            "per_query_relevance", "baseline_expectation", "semantic_truth_digest",
            "import_tree_sha256"
        ]
    });
    let queries = json!({
        "$id": format!("https://contextdesk.example/schemas/{RA_QUERYSET_SCHEMA_ID}.json"),
        "title": "ContextDesk retrieval-ablation query set",
        "schema_id": RA_QUERYSET_SCHEMA_ID,
        "schema_version": RA_QUERYSET_SCHEMA_VERSION,
        "authority": "crates/cd-core/tests/support/retrieval_ablation.rs::RaQuerySet (serde, deny_unknown_fields)",
        "model_safe": true,
        "query_kinds": [
            "broad", "causal", "symptom", "identifier", "negative", "competing",
            "chronology"
        ],
        "required": ["schema_id", "schema_version", "suite_id", "case_id", "queries"]
    });
    let run_record = json!({
        "$id": format!("https://contextdesk.example/schemas/{RA_RUN_RECORD_SCHEMA_ID}.json"),
        "title": "ContextDesk retrieval-ablation run record",
        "schema_id": RA_RUN_RECORD_SCHEMA_ID,
        "schema_version": RA_RUN_RECORD_SCHEMA_VERSION,
        "authority": "crates/cd-core/tests/support/retrieval_ablation.rs::RaRunRecord (serde, deny_unknown_fields)",
        "modes": ["structured_keyword", "hybrid_embedding", "hybrid_embedding_reranked", "full_multistage"],
        "mode_states": ["executed", "unavailable"],
        "accounting": "None = unknown (blocks when the capability was claimed); Some(0) = measured zero",
        "required": [
            "schema_id", "schema_version", "suite_id", "suite_version", "case_id",
            "tier_claimed", "mode", "mode_status", "engine", "corpus", "calls",
            "queries"
        ]
    });
    let report = json!({
        "$id": format!("https://contextdesk.example/schemas/{RA_REPORT_SCHEMA_ID}.json"),
        "title": "ContextDesk retrieval-ablation report",
        "schema_id": RA_REPORT_SCHEMA_ID,
        "schema_version": RA_REPORT_SCHEMA_VERSION,
        "authority": "crates/cd-core/tests/support/retrieval_ablation_scoring.rs::RaReport (serde, deny_unknown_fields)",
        "partition": [
            "PASS_ON_BASE", "BASELINE_LIMITATION", "FUTURE_CAPABILITY_UNAVAILABLE",
            "RED_REQUIRED_FIX"
        ],
        "determinism": "runtime_* and *_ms fields are informational and excluded from golden comparison; every other field is deterministic for a fixed (sha, suite, seed, tier, mode)",
        "required": [
            "schema_id", "schema_version", "suite_id", "suite_version",
            "contextdesk_sha", "generator_version", "seed", "tier_requested",
            "tier_actual_events", "corpus_identity_sha256", "modes", "cases",
            "partition_counts", "disclosures"
        ]
    });
    vec![
        ("retrieval-truth.v1.schema.json", truth),
        ("retrieval-queries.v1.schema.json", queries),
        ("retrieval-run-record.v1.schema.json", run_record),
        ("retrieval-report.v1.schema.json", report),
    ]
}
